### ISSUE TITLE
Nil-value of ReplaceAttr leads to crash

### ISSUE THREAD

**Issue by tobbee** [dusted-go/logging#2]
Thanks for a very nice handler and a nice blog post describing it.

I just tried it out and ran into a crash that took me some time to debug.

I followed your example:

```go
prettyHandler = prettylog.NewHandler(&slog.HandlerOptions{
    Level:       slog.LevelInfo,
    AddSource:   false,
    ReplaceAttr: nil,
})
logger := slog.New(prettyHandler)
```
and the code crashed on line 88 in prettylog.go
https://github.com/dusted-go/logging/blob/d9463cd16bc29441d9ec08d75fc49c5508cdb6df/prettylog/prettylog.go#L88

What I needed to do was to set `ReplaceAttr` to a trivial function that propagates the `levelAttr`, but I think it would be better that one has a check in the code whether `h.r == nil` and then skip the mapping, so that one can leave the ReplaceAttr function empty.

**Comment by berzileux** [comment]
@tobbee - do you have that trivial function that propagates the levelAttr

**Comment by berzileux** [comment]
replacer := func(groups []string, a slog.Attr) slog.Attr {
		if a.Key == slog.SourceKey {
			source := a.Value.Any().(*slog.Source)
			source.File = filepath.Base(source.File)
		}
		return a
	}

var prettyHandler = prettylog.NewHandler(&slog.HandlerOptions{
    Level:       slog.LevelInfo,
    AddSource:   true,
    ReplaceAttr: replacer,
})
logger := slog.New(prettyHandler)

 logger.Info(
  "incoming request",
  "method", "GET",
  "time_taken_ms", 158,
  "path", "/hello/world?q=search",
  "status", 200,
  "user_agent", "Googlebot/2.1 (+http://www.google.com/bot.html)",
 )

**Comment by tobbee** [comment]
This is what I used `f := func(groups []string, a slog.Attr) slog.Attr { return a }`

https://github.com/Dash-Industry-Forum/livesim2/blob/53093cba4d3032d9b6072f7034fd6361cfcd0f1c/pkg/logging/init.go#L29C1-L29C65

**Comment by dustinmoris** [comment]
oh amazing, thanks for raising the issue. I'll try to fix this later today!

**Comment by dustinmoris** [comment]
Thanks again, this should be fixed now!
