### ISSUE TITLE
Panic when logging after calling logger.With()

### ISSUE THREAD

**Issue by eneault** [dusted-go/logging#6]
Hi, the code panics since v1.2.0 when calling myLogger.Handler().Handle(...) after calling myLogger.With(...)

```go
ctx := context.Background()
myRecord := slog.NewRecord(time.Now(), slog.LevelInfo, "hello", 0)

// works ok
myLogger.Handler().Handle(ctx, myRecord) 

// add attributes
myLogger = myLogger.With(slog.String("abc", "def"))

// code panics
myLogger.Handler().Handle(ctx, myRecord) 
```

Previous versions were working fine.

**Comment by dustinmoris** [comment]
Sorry about this oversight and thanks for reporting. I just fixed the issue and created a new release and verified that it works again 👍
